DROP DATABASE IF EXISTS ABP;

CREATE DATABASE IF NOT EXISTS ABP;

USE ABP;

CREATE TABLE IF NOT EXISTS ROL(
  ID int(225) AUTO_INCREMENT NOT NULL,
  NOMBRE varchar(25) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS USUARIO(
  LOGIN varchar(25) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  NOMBRE varchar(25) NOT NULL,
  APELLIDOS  varchar(50) NOT NULL,
  GENERO varchar(10) NOT NULL,
  ROL_ID int(225) NOT NULL,
  PRIMARY KEY(LOGIN),
  FOREIGN KEY (ROL_ID) REFERENCES ROL (ID)
);

CREATE TABLE IF NOT EXISTS PAREJA(
  ID int(225) AUTO_INCREMENT NOT NULL,
  JUGADOR_1 varchar(25) NOT NULL,
  JUGADOR_2 varchar(25) NOT NULL,
  CAPITAN varchar(25) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (JUGADOR_1) REFERENCES USUARIO (LOGIN),
  FOREIGN KEY (JUGADOR_2) REFERENCES USUARIO (LOGIN),
  FOREIGN KEY (CAPITAN) REFERENCES USUARIO (LOGIN)
);

CREATE TABLE IF NOT EXISTS PISTA(
  ID int(225) AUTO_INCREMENT NOT NULL ,
  NOMBRE varchar(25) NOT NULL,
  TIPO varchar(25) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS HORARIO(
  ID int(225) AUTO_INCREMENT NOT NULL,
  HORA_INICIO time NOT NULL,
  HORA_FIN time NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CAMPEONATO(
  ID int(225) AUTO_INCREMENT NOT NULL,
  NOMBRE varchar(50) NOT NULL,
  FECHA date NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
  ID int(225) AUTO_INCREMENT NOT NULL,
  NIVEL int(5) NOT NULL,
  GENERO varchar(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CAMPEONATO_CATEGORIA(
  CAMPEONATO_ID int(225) NOT NULL,
  CATEGORIA_ID int(225) NOT NULL,
  PRIMARY KEY (CAMPEONATO_ID, CATEGORIA_ID),
  FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO (ID),
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
);

CREATE TABLE IF NOT EXISTS INSCRIPCION(
  PAREJA_ID int(225) NOT NULL,
  CATEGORIA_ID int(225) NOT NULL,
  PRIMARY KEY(PAREJA_ID, CATEGORIA_ID),
  FOREIGN KEY (PAREJA_ID) REFERENCES PAREJA (ID),
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
);

CREATE TABLE IF NOT EXISTS GRUPO(
  ID int(225) AUTO_INCREMENT NOT NULL ,
  NOMBRE char(1) NOT NULL,
  CAMPEONATO_ID int(225) NOT NULL,
  CATEGORIA_ID int(225) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO (ID),
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
);

CREATE TABLE IF NOT EXISTS RESERVA(
  ID int(225) AUTO_INCREMENT NOT NULL ,
  USUARIO_LOGIN varchar(25) NOT NULL,
  PISTA_ID int(225) NOT NULL,
  FECHA date NOT NULL,
  HORARIO_ID int(225) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO_LOGIN) REFERENCES USUARIO (LOGIN),
  FOREIGN KEY (PISTA_ID) REFERENCES PISTA (ID),
  FOREIGN KEY (HORARIO_ID) REFERENCES HORARIO (ID)
);

CREATE TABLE IF NOT EXISTS ENFRENTAMIENTO(
  ID int(225) AUTO_INCREMENT NOT NULL,
  GRUPO_ID int(225) NOT NULL,
  RESULTADO varchar(25),
  PAREJA_1 int(225) NOT NULL,
  PAREJA_2 int(225) NOT NULL,
  RESERVA_ID int(225),
  PRIMARY KEY(ID),
  FOREIGN KEY (PAREJA_1) REFERENCES PAREJA (ID),
  FOREIGN KEY (PAREJA_2) REFERENCES PAREJA (ID),
  FOREIGN KEY (RESERVA_ID) REFERENCES RESERVA (ID),
  FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO (ID)
);

CREATE TABLE IF NOT EXISTS HUECO(
  ID int(225) AUTO_INCREMENT NOT NULL,
  FECHA date NOT NULL,
  ENFRENTAMIENTO_ID int(225) NOT NULL,
  PAREJA_ID int (255) NOT NULL,
  HORARIO_ID int(225) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (PAREJA_ID) REFERENCES PAREJA (ID),
  FOREIGN KEY (ENFRENTAMIENTO_ID) REFERENCES ENFRENTAMIENTO (ID),
  FOREIGN KEY (HORARIO_ID) REFERENCES HORARIO (ID)
);

CREATE TABLE IF NOT EXISTS CLASIFICACION(
  ID int(225) AUTO_INCREMENT NOT NULL,
  PAREJA_ID int(225) NOT NULL,
  PUESTO int(225) NOT NULL,
  PUNTOS int(225) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (PAREJA_ID) REFERENCES PAREJA (ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIA_CLASIFICACION(
  CATEGORIA_ID int(225) NOT NULL,
  CLASIFICACION_ID int(225) NOT NULL,
  PRIMARY KEY (CATEGORIA_ID, CLASIFICACION_ID),
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID),
  FOREIGN KEY (CLASIFICACION_ID) REFERENCES CLASIFICACION(ID)
);

CREATE TABLE IF NOT EXISTS GRUPO_CLASIFICACION(
  GRUPO_ID int(225) NOT NULL,
  CLASIFICACION_ID int(225) NOT NULL,
  PRIMARY KEY (GRUPO_ID, CLASIFICACION_ID),
  FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO (ID),
  FOREIGN KEY (CLASIFICACION_ID) REFERENCES CLASIFICACION(ID)
);

CREATE TABLE IF NOT EXISTS PARTIDO(
  ID int(225) AUTO_INCREMENT NOT NULL,
  FECHA date NOT NULL,
  RESERVA_ID int(255),
  PISTA_ID int(255),
  HORARIO_ID int(255),
  INSCRIPCIONES INT(1) NULL DEFAULT '0',
  PRIMARY KEY(ID),
  FOREIGN KEY (RESERVA_ID) REFERENCES RESERVA (ID),
  FOREIGN KEY (PISTA_ID) REFERENCES PISTA (ID),
  FOREIGN KEY (HORARIO_ID) REFERENCES HORARIO (ID)
);

CREATE TABLE IF NOT EXISTS USUARIO_PARTIDO(
  ID int(225) AUTO_INCREMENT NOT NULL ,
  USUARIO_LOGIN varchar(25) NOT NULL,
  PARTIDO_ID int(255) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO_LOGIN) REFERENCES USUARIO (LOGIN),
  FOREIGN KEY (PARTIDO_ID) REFERENCES PARTIDO (ID)
);
